version=0.0.1
group=com.nstut.worldengine
java_version=21

# Mod properties
minecraft_version=1.21.1
mod_name=World Engine
mod_author=NsTut
mod_id=worldengine
credits=Built as an optimization addon for Sable by RyanHCode and contributors
license=All Rights Reserved
description=World-scale physics and simulation optimizations for Sable.
issues=https://github.com/UpperMoon0/World-Engine/issues
minecraft_version_range=[1.21.1]
sable_version=2.0.4

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.110.0+1.21.1
fabric_loader_version=0.16.9

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.1.228
neoforge_loader_version_range=[4,)

# Sable API dependencies
sable_companion_version=1.6.0

loom.ignoreDependencyLoomVersionValidation=true

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
